utils/sql/git/required/2023_09_24_mistwalker_temp_pet.sql

change `max1` to whatever value for number of seconds the pet should be active.
I noticed in testing that at 3 seconds sometimes the pet wouldn't get a round in before poofing. May be need 4? Idk value you want to use.
The other solution is the pre-nerf change found here https://github.com/SecretsOTheP/EQMacEmu/pull/22

mistwalker temp pet

---

zone/aggro.cpp

The community has agreed that self found players should be able to buff "normies" aka non-self found players.
[Link To Discord Discussion](https://discord.com/channels/1133452007412334643/1137154675267883079/1160431493894639647)
Tested logic with [github.com/Vanifac](https://github.com/Vanifac/), have not tested on server, but seems like a simple change.
```
C1 - not self found  C2 - not self found  - skips the block (doesn't fail)
C1 - self found C2 - not self found - skips the block (doesn't fail)
C1 - not self found C2 - self found - fails - not allowed - returns false
C1 - self found C2 - self found - returns false if they are not in level range
```
This keeps in the restriction that normies can not buff self found players

Allow self found players to buff normies (non self found)

---

zone/aggro.cpp

Keep intact the logic that no one can buff solo players.
This keeps it in line with change #37

Allow solo players to buff other players

---

README.md

The links were pointing to the takp versions, hopefully this can help make things more clear for future people.
Wasn't 100% sure on the Maps one, so didn't change it

Update Readme with Quarm Links

---

zone/client_packet.cpp

Allow normies to pick up items dropped by sf and ssf players
The community consensus is this should be allowed.  
Example 
- An SSF or SF necro manages to get an SSOY.  
- They can't use the item, but don't want it to go to waste. 
- They gift the item to another player by dropping it on the ground
This solution is nice because we still have trading disabled for SSF and SF players, but allows gifting of items to normies.

Allow normies to pick up items dropped by sf and ssf players

---

zone/attack.cpp

Updated hardcore death broadcast message to include all of the character's challenge rulesets so we know exactly how impressed and sad to be for them.
Before: `[Hardcore] Larry has died! They were level 28.`
After: `[Hardcore Self Found] Larry has died! They were level 28.`
Idea suggested in Discord [here](https://discord.com/channels/1133452007412334643/1138575471366377603/1164687250727116832) 
Regarding lines 32xx: My IDE corrected an inconsistency in the End of Line characters. Those lines had CRLF (\r\n) while the rest of the file had only LF (\n\). My IDE made those consistent. In noticing this [we also figured](https://discord.com/channels/1133452007412334643/1161485739293429830/1165155057885524019) moving the curlies and putting the nested method call on one line was more …

include all rulesets in hardcore death broadcast

---

zone/groups.cpp

Self found should not be allowed to manually /split in any case.
Added a simple check to see if it's a manual /split. if it is check to see if the splitter is self found. Return if it is.

Remove the ability to /split for self found characters.

---

zone/client_packet.cpp

Exploit was that if a player dropped the items before they flagged ssf, then they could pick them up after respawning as ssf.  That's no longer possible

Re-enable dropped items for SSF and fix exploit

---

common/eq_stream.cpp
common/eq_stream.h
common/eq_stream_factory.cpp
common/eq_stream_factory.h

- converted Mutex -> std::mutex, std::lock_guard, std::unique_lock
- converted Conditional -> std::condition_variable
- converted to use std::thread
- separated all mutex into corresponding EQOldStream & EQStream
- separated thread functionality into corresponding EQOldStream & EQStream
- ReaderThread
- ProcessNewThread
- WriterNewThread
- ProcessOldThread
- WriterOldThread
- fix for UCS
- fix for lag encountered when EQ is unfocused (https://github.com/SecretsOTheP/EQMacEmu/pull/56/commits/2be836b3fc19f16fc0812908e83752e1ba0bb17f)
- tested by: compiling on mscv & gnu, verifying cpu usage is acceptable, running & playing on both windows & linux environments

EQOldStream & EQStream updates & processing separation (eq_stream & eq_stream_factory) & lag issue fix

---

common/eq_stream_factory.cpp
common/eq_stream_factory.h

- moving various Stop & Signal functions to .cpp
- terminate crash fixes:
- for joining threads, need to make sure they're still joinable
- typo for StopWriterNew, StopWriterOld these weren't using the unique_lock
Tested by:
repro: Sending interrupt signal to zone process, verifying there is a crash
fix: Sending interrupt signal to zone process, verifying no longer crashing
Also tested by sending interrupt signal to world process to make sure it isn't crashing as well

eq_stream_factory Close fixes

---

common/servertalk.h
queryserv/database.cpp
queryserv/database.h
queryserv/worldserver.cpp
utils/sql/git/required/2023_11_22_qs_player_speech_additions.sql
zone/client.cpp
zone/command.cpp
zone/groups.cpp
zone/groups.h

- additions to log information for:
- up to 5 group members
- groupid
- characterid
requires: `utils/sql/git/required/2023_11_22_qs_player_speech_additions.sql` applied
note: https://github.com/SecretsOTheP/EQMacEmu/compare/main...chazix:EQMacEmu:qs-player-speech-additions?expand=1#diff-8541f36e60ccf19a8ff067c78dd04929f95503850299a869b54fd28e49fb8ed1R749
- The `targetname` wasn't being propagated as `nullptr` when I would target a player client. It was being propagated as an empty string of length 0
Tested by:
- forming a group of 6 clients locally; tested with these steps from 2->6 clients as they were joining
- having each one send a message to the group
- verifying the functionality was applied in the db

qs_player_speech logging additions

---

zone/client.cpp

- revert `targetname` isolated change, preserving `targetname` conditional as it was before
- retrieve `logTargetName` independently in the `PlayerLogChat` process
- new: a guild message `logTargetName` will be the name of the guild
- new: auction, ooc, shout `logTargetName` is the zone shortname
Tested by:
- before fix: creating 2 guilds, having a client from another guild target the other client in different guild, sending guild message to other client, seeing that the other client receives a guild message from the non-member client
- after fix: verified original functionality is restored, and no target based guild messages
- `/say` w/ & w/out a target, verified `to` in `qs_player_speech` table
- `/tt`, `/tell`, verified `to` always the recipient
- `/gu`, verified `to` is always guild …

Chat targetname preservation & PlayerLogChat target isolation

---

common/json/json.h
common/json/jsoncpp.cpp
utils/sql/git/required/2023_11_25_qs_player_ks_log.sql
zone/attack.cpp
zone/hate_list.cpp
zone/hate_list.h
zone/queryserv.cpp
zone/queryserv.h

- Functionality to track initial engage ids, and determine if a kill steal has occurred
- if a kill steal has occur, this will log to the: `qs_player_ks_log`
- example data:
```
npc_type_id;zone_id;killed_by_id;killed_by_group_id;killed_by_raid_id;initial_engage_ids;npc_lootables;time
4517;4;50373;0;0;{"groupId":0,"disbanded":[],"ids":[50378],"raidId":0}
;{"copper":0,"gold":0,"items":[13067,13070],"platinum":0,"silver":0}
;2023-11-25 02:12:24
4507;4;50373;0;0;{"groupId":4,"disbanded":[50378,50373],"ids":[],"raidId":0}
;{"copper":0,"gold":0,"items":[13408,13071],"platinum":0,"silver":0}
;2023-11-25 02:17:04
```
- Edge case situation:
- if 2 members are in a group
- 1 member leaves while engaged
- both members would no longer be in a group
- both members proceed to get added to `disbanded`, …

Feature: Kill Steal Tracking & Logging

---

zone/special_attacks.cpp

Backstab was granted a minimum damage in November 1999.  We had the level 51-59 and 60+ minimums in but 1-50 escaped my notice for whatever reason.

Backstab min damage fix

---

zone/hate_list.cpp
zone/hate_list.h

- functionality to be able to erase & reset initial engage `m_ids`, `m_disbanded` when a client zones
- whether by dieing, fd or otherwise
- allows other engagers to not be marked as potential ks
- whoever makes the next (solo/group/raid) hit is the next valid initial engager
- removed the PetID tracking as this isn't needed
- just need to keep track of root client CharacterID
Tested By:
- All prior test cases in previous pull request (https://github.com/SecretsOTheP/EQMacEmu/pull/66)
- Additional:
- 1st solo client engages mob, 2nd solo client engages same mob, (1) dies & zones, (2) kills mob: no ks is determined & no log
- 1st solo client engages mob, 2nd solo client engages same mob, (1) runs to zone, (2) kills mob: no ks is determined & no log
- 1 solo mage client engages & sends pet, …

Feature: Kill Steal Tracking & Logging (Zoning Handling)

---

zone/client.h
zone/exp.cpp

Light blue exp was broken in group splits because it was not properly calculating the level difference between the highest group member and the killed NPC for group members other than the highest level guy.  This would result in only the highest level guy getting the higher amounts of light blue exp and the lower level players would only get 20%.
Also when calculating raid exp, the con color was being determined on an individual basis instead of using the highest level player in the raid, which was resulting in lower level players getting exp from light blue kills as if they were dark blue.

Light Blue Con Exp Fixes

---

common/ruletypes.h
utils/sql/git/required/2024_01_18_alter_zone_table_add_banish_fields.sql
zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/zone.cpp
zone/zone.h
zone/zonedb.cpp
zone/zonedb.h
zone/zoning.cpp

This change will load and attach a zone banish point to each zone.
The zone banish points are populated at zone load time by looking at the doors with `guildzonedoor=1` leading to the zone and storing the book location (zone, x, y, z, heading).
This can be changed later if we want a different system.
Added a grace timer defaulting to 1 minute after zone before being booted out.

banish to book from guild instance (instead of bind)

---

zone/mob.cpp
zone/mob_ai.cpp

This was done because NPC types have level ranges and sometimes these ranges cross the threshold of summoning and enrage.  Previously the only way to handle this was to duplicate the NPC type and apply the special ability to one type and not the other, but this clutters up the database.  So I hardcoded level checks to fail summon and enrage if the NPC was under the threshold levels even while having the special abilty set.  Currently we have some planar mobs not summoning at all when they should be due to this problem.
I would have checked the maxlevel field but that is not accessible from the Mob class and adding new methods for this would add more clutter so I just checked if the NPC is level 48-50 and 53-55.

Added some level checks to summon and enrage

---

zone/spells.cpp

Currently, the self found buff checks are broken, allowing a higher level character to cast buffs on a lower level character but not the other way around. This is backwards to how it should be.
Changing IsInLevelRange() to verify that the spell_target can get EXP while with the caster should fix this instead of the other way around.

Fix for Self-Found level check when buffing.

---

zone/mob.cpp
zone/pets.cpp

When Iksar Necromancers or Shadow Knights summon skeletal pets, they will be Iksar skeletons.
When Iksar Necromancers cast Lich or Demi Lich, they will turn into Iksar skeletons.
~Icestorm

Allow Iksar skeleton models in IKS NEC/SHD pets and IKS NEC lich.

---

zone/aggro.cpp

There are a few spells in the game which have poison or disease counters and a stun component, like Asystole.  The previous aggro logic was double the aggro on these few spells from adding the standard hate twice.  I could find no evidence to suggest that these spells should do more hate than a typical spell.

Standard hate from spells no longer stacks

---

zone/exp.cpp

Note that this commit will result in some players who are levels 60 to 64 to end up one level higher than they were, as it changes the amount of experience for these levels.  Quarm shouldn't have a problem with this since we're still in classic era.  TAKP on the otherhand will have this problem, so I didn't push this there.  However these are the precise hell_mods and TAKP needs to have them eventually.

hell_mods for levels 60-65 made accurate

---

zone/exp.cpp

The hell level smoothing done in Luclin reduced the amount of experience gained in these levels because these levels are short.  This results in deaths in these levels being harsher than typical.  Since these levels are the max levels at their respective eras, it makes sense to override their HBMs until they're no longer the max level, particularly when leveling smoothing was a mid to late Luclin era addition.
Before this commit, players had their exp reduced by 25% in these levels.  After this commit that penalty goes away until the max level achieveable is higher than these levels.

Overrides for level 50 and 60 HBMs

---

common/spdat.h
zone/spell_effects.cpp

This is a hack to make Maestro's AoE heal.  I couldn't think of a better way to do this.
Changing the targettype to 20 in the database would probably work but people seem to frown upon editing spells.

Hardcoded Maestro AoE to heal him

---

zone/spells.cpp

This commit alters the resist spell method to try and mimic the classic, pre-September 2002 resists while keeping the 0-200 scale and -resist adjusts on spells.  Switching to the 0-99 scale would be too disruptive and troublesome to implement and would require a lot of database changes, so maintaining much of the PoP era system was desirable.  These changes are all gated to late Luclin and earlier.
Changes in this commit:
* Lifetaps on client targets are unresistable.
* Resist hardcap of 250 in Classic and Kunark eras, 350 after Kunark.
* Softcap at 200, overcap returns are half.
* Dragon breaths with a lure component hardcoded to be -100 instead of -150.
* Immolating Breath and Stun Breath hardcoded to be granted resist modifiers.
* Enchanter NPCs will be able to land spells on high …

Pseudo-Classic Resists

---

zone/buffstacking.cpp

Prevents all Splurt line spells from attempting to heal target on first tick and assigns proper damage instead.

Fix for Splurt line missed tick

---

utils/sql/git/content/2024_07_20_Add_Decrepit_Hide_Dracoliche_Fear.sql
utils/sql/git/content/2024_07_20_Increase_Decrepit_Hide_SHD_Epic_Hate.sql
utils/sql/git/content/2024_07_20_Increase_Epic_Mob_Spawns_Instanced_Fear.sql
utils/sql/git/content/2024_07_20_Increase_Essence_of_Vampire_ENC_Epic_Hate.sql
utils/sql/git/content/2024_07_20_Increase_Soul_Leech_Hate.sql
utils/sql/git/content/2024_07_20_OT_Hammer_Skeleton_Deagro.sql

- Change chance of ashenbone drakes in hate to drop SHD epic component 'Decrepit Hide' from 19% to 38% 
- Fix respawn timers for Epic mobs in Plane of Fear 
- Change chance of male revenants in hate to drop ENC epic component 'Essence of a Vampire' from 1% to 9% 
- Change probability of Cazic Thule in fear to drop SHD epic component 'Soul Leech' from 50% to 100% 
- Fix aggressive skeleton by using spawn with no faction on boat where players port in from using Worker Sledgemallet (Overthere proc)

Database content updates

---

utils/sql/git/content/2024_07_27_Chardok_Soultrapper_Pet_In_Wall_Fix.sql

Fixed spawnpoint for a Shai`din Soultrapper in Chardok so when it summons a pet, that pet is no longer stuck in the wall causing players to crash when targeting it.

Update Chardok spawngroup that is too close to the wall and causing problems

---

zone/effects.cpp

When a raid is using a PBAE strategy, remove raid member pets from the list of valid targets in order to preserve the maximum targets allowed cap.

Prevent PBAE from targeting raid pets.

---

utils/sql/git/required/2024_07_29_Fix_Loading_Zones_For_Instance_Zoning.sql
zone/zoning.cpp

* Fixed a bug where teleporting from an instance of zone to the non-instanced version of the zone would send player to the safe coordinates of the instanced zone and lock their spell gems.

Fixed zoning from an instance to the same non-instanced zone.

---

utils/sql/git/content/2024_08_03_Fix_Power_of_Fire_Ungate_Mobs_and_Spells.sql

- Reverted Power of Fire drop on blazing elemental back to 9% from 1.5% post-merge.
- Returned spawns of an angry goblin, a goblin traitor, and a sarnak spy after merge gated them.
- Returned Spell: Strength of Nature after merge gated it.

Updated Power of Fire drop and Ungated several mobs and Ranger spell.

---

utils/sql/git/content/2024_08_04_Ungate_Undead_Dragon_Sinew_Fix_CT_Zone_Spawns.sql

- Restored Undead Dragon Sinew to drop tables for Trakanaon and Juggernauts.
- Restored spawn chance for Cazic Cenobite in Cazic Thule.
- Restored spawn chance for Avatar of Fear in Cazic Thule.
- Restored spawn chance for Tae Ew Archon in Cazic Thule.
- Restored spawn chance for Tae Ew Templarin Cazic Thule.
- Restored spawn chance for Tae Ew Diviner in Cazic Thule.
- Restored spawn chance for a steel golem in Cazic Thule.
- Restored spawn chance for a stone golem in Cazic Thule.
- Restored Stoneleer Emerald Plume on stoneleer cockatrices.

Updated Undead Dragon Sinew and Spawns in Cazic Thule

---

zone/mob_ai.cpp

- Allows raid encounter NPCs to use their special abilities/spells properly and timely.

TAKP provided correction for raid boss priority abilities/spells

---

utils/sql/git/content/2024_08_06_Ungating_and_Drop_Chance_Fixes.sql

- Fixed Essence of Vampire, previously fixed but was modified by The Great Merge
- Ungated Thick Caustic Fluid
- Ungated an Iksar tomb raider in Emerald Jungle
- Ungated Marthor for Monk Whistling Fists questline
- Ungated Hierophant Granix for Shaman Skull Quest
- Ungated Gandan Tailfist for Monk Whistling Fists questline
- Ungated Annaelia Wylassi for Monk Whistling Fists questline
- Ungated a fallen monk for Monk Whistling Fists questline
- Ungated Crusader Vragor for Monk Whistling Fists questline

Ungating and drop updates

---

zone/attack.cpp

Fixing Luclin AC softcap bug to what I assume is the intended logic.
By the current logic, once Luclin becomes enabled, any player that exceeds AC softcap would all of a sudden have their AC reset to 12.

Fix Luclin AC Softcap Calculation Typo

---

utils/sql/git/content/2024_08_15_Revert_Starting_Character_Items.sql

TAKP Merge placed starting characters at 5 bread/milk + discord tome.  Reverting back to how it was originally on PQ (20 bread/milk and no tome).

Revert starting character items back to 20 bread/milk

---

zone/aggro.cpp

Fix potential exploit that could allow group buffs to land while dueling

Check ssf beneficial spell restrictions before /duel rules

---

zone/spells.cpp

- For sf players, check exp level range during pre-casting check i.e. fail spell early
- Make bind affinity and group teleports castable between out of xp level range sf players

Sf spell rules

---

zone/attack.cpp
zone/client.cpp
zone/client.h
zone/corpse.cpp
zone/corpse.h
zone/hate_list.cpp
zone/npc.h

Fixes:
- Player unable to loot if he dies during raid encounter
- Player unable to loot during last 4 minutes during which anyone can loot

Fix sf loot issues

---

zone/corpse.cpp

#148 addressed the issue of corpses locking for regular sf groups. This PR addresses it for sf raids.

Don't lock sf raids from looting during last half of corpse timer

---

zone/attack.cpp

`NPC::Death` and `NPC::CreateCorpse` have slightly different logic for determining whether an sf player gets kill credit, both based on how much damage was done by damage shields. This resulted in situations where a magician chain healing his fire pet would get exp but not loot rights.
This change makes the damage shield check for loot match the damage shield check for exp.
Here is the other damage shield check for exp.
https://github.com/SecretsOTheP/EQMacEmu/blob/54a174ed7191dea7b4c4a420f4f4012fff6e4da5/zone/attack.cpp#L1994

Fix bug where ssf using ds would get exp but not loot rights

---

common/ruletypes.h
common/spdat.cpp
common/spdat.h
zone/attack.cpp

Lich damage mitigation bound by quarm rule to fix live damage discrepancy.
Tested on my dev world against current origin/main base.
Set Quarm:LichDamageMitigation to true to enable it.

Lich damage mitigation bound by quarm rule

---

zone/spells.cpp

Fix for https://discord.com/channels/1133452007412334643/1169044978777989182/1169044978777989182

Fix self/group spells being interrupted when target is sf player

---

zone/spells.cpp

Fixes issue where spells like selos or clickies like jboots that are ST_Self are interrupted with a message that the spell cannot affect the target npc.

Fix self/group spells being interrupted when target is an immune npc

---

common/database.cpp
zone/client_packet.cpp

TLDR: Minor change that decouples the "Max 1 Accent" and "Max 2 capitalization" checks into separate checks, based on the evidence/use-cases cited below. Current logic only allows a 2nd capitalization immediately after an accent, but evidence shows that, in practice, players were allowed a 2nd capitalization without requiring a preceding accent per their supported naming policies.
- Adjust surname validation to closer match Daybreak's historical naming policy (read below).
- Server will reject badly capitalized surnames instead of forcing to lowercase and approving (Prevents user error, try again).
(1) https://forums.daybreakgames.com/eq/index.php?threads/surname-support-help-co-devs.232050/
This post shows that from 1999-2016, SOE/Daybreak actively supported the following surnames in …

Updated surname rules to better simulate Daybreak's naming policy

---

zone/attack.cpp

NPC damage is now added to the self found dmg credit calculation. Affects self found only.
Test Method:
- Using enchanter to charm a mob, attack another mob and let them fight.
- When charmed mob is low, break charm with invis
- Nuke charmed mob
- Notice XP is now given and before this change it was not
Fixes this issue: https://discord.com/channels/1133452007412334643/1234352510060462161

Fix self found charmers not getting xp for killing their own pets

---

zone/zonedb.cpp

I believe this was probably broken for any class where the zone they are bound is different from their starting zone
Bug report link: https://discord.com/channels/1133452007412334643/1293936046974828635

Fix self found iksar not getting guild summons

---

utils/sql/git/content/2024_10_16_Increase_Heartsting_Sack_Drop_Rate.sql

See discussion here for reasoning & community support: https://discord.com/channels/1133452007412334643/1295814305660538901
11 upvotes, no downvotes, no comments arguing against.  Makes farming for slow poisons a little easier from 1 per hour to 3-4 per hour and reducing zone disruption.
Tested by going around FoB pit and killing regular heartstings.  I was getting one every 4 mobs on average.  Mostly like 5, 4, 4, 5, 2, etc
On large heartstings my rng was a little worse running around, they seem to be a rarer spawn too.  When spawned with the spawn command though, I made 6 of them and 2 of them had the sack, so that seems to align well with the intended drop rate.

  Update heartsting sack drop rate from 15-30%

---

utils/sql/git/content/2024_10_19_Field_of_Bone_Spiders_Drop_Increase.sql

Increase from max 2 to max 4.
Change was already made on takp, but waiting on merge.  I figured I'd go ahead and implement it here since it'll be such a boon for the cash poor iksar newbs.
Discussion thread: https://discord.com/channels/1133452007412334643/1291440098260287549
Implemented by changing the multiplier for this lootdrop_entry to 4 from 2.
Tested by running the script, restarting field of bone, running around doing `#npcloot show` to all  of the spiders to confirm they have 0 - 4 silks.
Also double confirmed by changing the multiplier value to 100 in the updates & selecting all rows that are 100 and it only showed the spider silk for these two, so can confirm it only updated those two rows

Increase drop rate of spider silk for spiders in field of bone

---

common/ruletypes.h
zone/spells.cpp

They are no longer resisted 20% by default & no longer prevented from killing mobs.
Also added rules in case these end up being too unbalanced so they can be turned back on easily
Tested by setting level to 24, using Lightning Storm, killing Sarnak Recruits. Some resists, but significantly less than before the change.
Also tested by killing orc centurions and legos in Crushbone while at level 24. No resists at all, which is to be expected for lower level mobs.
Also confirmed that this spell breaks root quite often so probably not that useful as a solo spell.
Feature request & discussion can be found here: https://discord.com/channels/1133452007412334643/1234431884004687942
22 upvotes, 4 downvotes but it makes sense to me.  Wizard rain spells have always sucked and this might improve …

Slightly improve wizards rain spells

---

utils/sql/git/content/2024_10_17_Increase_Bard_Paladin_Epic_Drop_Rate.sql

Discussion thread from Discord suggestions: "Boost drop rates or spawn rates for epic items that are 7 day locked."
- https://discord.com/channels/1133452007412334643/1296549150183260221
5 Updoots / 0 Down, and Ailia showing support as well. The discussion scope is broader than just this change, but Bard/Paladin are biggest outliers in need of attention.
- Naggy/Vox will always drop 1 Scale and 1 Book.
Bard/Paladin epic drops were exceedingly rare compared to most other classes.
Most other class drops have been added as 100% drop chances from CT/Inny/Chardok/Fay/Hate trash/Sky trash, etc. Reliably completing 1/week.
Bard/Paladin are especially bad since it's a 7 day lockout with only a rare chance of the drop.
I can vouch for this being a big issue from personal experience. Had to wait, …

Increase Bard/Paladin Epic Drop Rate Bottlenecks

---

utils/sql/git/content/2024_10_17_Morning_Dew_Vendor_Cost.sql

This implements suggestion: https://discord.com/channels/1133452007412334643/1267554989203525703
4 upvotes, 1 100% emoji and no downvotes.  The main idea is to incentivize players to sell their foraged morning dew so crafters can do vendor diving to find more mats like they can for other cultural armor.
Sell price at amiable is 7 silver, 1 copper.  Purchase price is 9 silver.
Tested with both GM summoned item & actually foraging one to double check that both work.

Add a small cost for Morning Dew so it can be sold to merchants

---

utils/sql/git/content/2024_10_29_Reduce_Iksar_Shaman_Kurns_Skull_Bottleneck.sql

Requested & discussed here: https://discord.com/channels/1133452007412334643/1277260041648345088
Math is outlined in the sql file to see how we arrived at these numbers.
Increase drop rate of lore item from 10->17% chance
Increase spawn rate of crusader from 10->25% chance
Reduce drop rate of fine steel from 100% -> 40% to adjust for higher spawn rate, so platinum per hour will stay around the same
Tested by doing:
#hotfix aaa
#reloadworld 1
#zone gfaydark
#zoneshutdown kurn
#zone kurn
Then lots of #repop and #listnpcs undead_crusader
Then murdering them and seeing how long it takes to finish the quest.  Also confirmed drop rate of the fine steel is less than 100%, but still decently often.

Increased the speed at which shamans can complete kurn skull quest

---

utils/sql/git/content/2024_10_30_Balance_Iksar_Monk_Kurns_Fingers.sql

It was only taking 30 minutes on average to complete and now will be 1 hour on average to bring it in line with the shaman iksar skulls of similar difficulty
Drop rate was also increased previously & that change is staying in place, so it's still significantly buffed from the original
Previously was 25% which was deemed too much of a bottleneck
Source link: https://discord.com/channels/1133452007412334643/1294349487765979287
Source link pre-buff: https://discord.com/channels/1133452007412334643/1270799693122895882

Update monk kurn fingers to drop 50% chance instead of 100%

---

zone/client_packet.cpp

Suggestion Link: https://discord.com/channels/1133452007412334643/1293991185844539494
Tested by launching 3 clients. First client starts group with 2nd client.  First client invites 3rd client, observe 2nd client sees a message that 3rd client was invited.

Add notification to all group members when someone is invited

---

zone/forage.cpp

The incorrect heading was making it so your fishing line was being cast in the wrong direction.  For example standing East on the east freeport docks was casting the line to the southwest
Tested by both confirming multiple locations was able to fish vs not fish correctly.  There's a little funkiness on the EFP docks still because the line of sight check doesn't seem to check the dock. That's probably fine though. This at least fixes the majority of the issues.
Also double checked the headings in the logs, the locs it was trying to check, etc
Bug report here: https://discord.com/channels/1133452007412334643/1296854405034803231

Fix fishing using the wrong heading

---

utils/sql/git/content/2024_10_31_Fix_Monk_Thunderkick_Typo.sql

This apparently might not be classic, but seems like it would make sense to fix it
Bug report: https://discord.com/channels/1133452007412334643/1301306881209270343

Fix typo in monk thunderkick discipline

---

zone/spell_effects.cpp

This packet adjustment fixes the client so songs expire consistently on the server tick, rather than on the desynced client tick.
- Server makes the client think/notice the song is 18 sec duration (+1 tick), so the client will wait for the server to expire the buff.
- No changes to the actual buff expiration logic on the server, this is only a visual/info change sent to the client to make it behave.
Eventually maybe we can get Zeal to implement a way to sync client ticks to the server, which would fix how the buff timers are decrementing independently of the server ticks.
- Buffs properly expire on the server tick (white bar).
Based on when you logged in, your client tick desync would affect nearly every song duration until you logout/zone. If you had a bad client tick, every song would …

Fix songs to expire consistently on server tick rather than client tick

---

zone/client_packet.cpp

Currently it sends a message to each member of the group that you invited someone, but you as the sender don't know that.  This updates it so the sender now knows there's an automated message being sent
Bug report: https://discord.com/channels/1133452007412334643/1161485739293429830/1302192136141279242

Update group invite to notify sender too

---

common/inventory_profile.cpp
zone/inventory.cpp

This will include the suggestion made for Staff of Null as well as other lighted items like candles, etc
This was working with a certain set of items like Greater Lightstone already, but I think it's hardcoded into the client to update those and not others.  I couldn't find a reason why the light was updating via server code for Greater Lightstone when it was put into an inventory slot using logs.
Instead of this, whenever an item is put into the general inventory, if it has light, we check to see if the client's light source should be updated and if so, then send the packet to update.
Suggestion thread: https://discord.com/channels/1133452007412334643/1277581221697814538

Add support for any lighted item to shine from inventory slots

---

utils/sql/git/content/2024_11_05_Remove_Verina_Tomb_Faction.sql

Resolves Suggestion https://discord.com/channels/1133452007412334643/1280584443752353801
The major problem with this is that human clerics of Innoruuk are sent to Neriak as their primary guild and have to walk right past her to do quests and buy spells.
Those clerics were getting killed bc she's always up now due to easy epics

Remove faction from Verina Tomb

---

common/servertalk.h
world/cliententry.cpp
world/cliententry.h
world/clientlist.cpp
zone/client.cpp

Each of these would be separate commands
These changes were previously submitted, merged and then reversed due to unknown performance issues at the time. I don't think reversing this commit fixed the performance issues, so now that things are more stable, hopefully this can be added again.  Feel free to revert if performance issues come back up and we can take a look at them.
Tested by making multiple characters with different combinations of hardcore, solo and self found flags.
Once they were logged in, used /who all solo, /who all selffound, /who all hardcore to find these players and the filtering was working properly

Add support for /who all for selffound hardcore & solo

---

utils/sql/git/content/2024_09_19_Forageables_for_Self_Found.sql

The west karana spawns are slightly broken without the tkap merge. Some spawns will not be able to be picked up when clicked.

Forageables for self found

---

zone/spells.cpp

Maybe I'm reading this wrong, but it seems like the charisma check for lull resists causing aggro is backward: `!zone->random.Roll(aggroChance)`
If my aggro chance is 100 because I have -40 charisma, then .roll(100) will always return true, and the ! makes it false, so I'd never get aggro. If my aggrochance is 0 (360 CHA). I'd ALWAYS hit the addToHateList block. But Maybe I'm reading this wrong, haven't written C since college

Charisma check on  lull resists seems flipped

---

common/spdat.cpp
common/spdat.h
zone/client.cpp
zone/client_packet.cpp
zone/mob.h
zone/spells.cpp
zone/zoning.cpp

Prevent removal of persistent buffs in the following scenarios:
- Zoning at low HP (where HP bonus from items exceeds remaining HP)
- Zoning into Plane of Air
- Being Sacrificed by another player

Fix some cases where persistent buffs are removed

---

utils/sql/git/content/2024_12_21_Demi_Lich_Skullcap_Happy_Holidays.sql

Required SQL to add Demi Lich Skullcap to Project Quarm.
Required quests (2 NPCs) also need to be pulled as well, published in separate PR.

Added Demi Lich Skullcap to PQ

---

common/CMakeLists.txt
common/inventory_profile.cpp
common/inventory_profile.h
common/item_instance.cpp
common/item_instance.h
common/loot.h
common/quarm_item_data.h
common/ruletypes.h
common/shareddb.cpp
common/shareddb.h
zone/client.h
zone/client_packet.cpp
zone/corpse.cpp
zone/corpse.h
zone/inventory.cpp
zone/loot.cpp
zone/npc.cpp
zone/npc.h
zone/object.cpp
zone/spell_effects.cpp
zone/trading.cpp
zone/zonedb.cpp

Quick Test:
(1)
- Player 1 (Non-SSF) Gave **Combine Dagger** to A Bat.
- Player 2 (SSF) Gave **Rusty Short Sword** to A Bat.
- Player 2 (SSF) Kills the Bat.
- Player 2 (SSF) able to loot **Rusty Short Sword**
- Player 2 (SSF) CANNOT loot **Combine Dagger** (Player 1's item)
(2)
- Player 2 (SSF) Casts **Sword of Runes** on their pet charmed with puppet strings. Pet equips the Sword of Runes.
- Player 2 (SSF) Kills their pet.
- Player 2 (SSF) Loots **Sword of Runes**
(3)
- Player 2 (SSF) Casts **Summon Phantom Leather** on their charmed pet. Pet equips the whole satchel of gear.
- Player 2 (SSF) Kills their pet.
- Player 2 (SSF) Loots each summoned item from the corpse.
Adds the groundwork for future SSF/Quarm-specific item features. But easier to split this up into smaller chunks.
This …

Feature - S/SF charm pet item loot support.

---

common/ruletypes.h
zone/client.cpp
zone/entity.cpp
zone/gm_commands/showhelm.cpp
zone/mob.cpp

The big ol' helm patch that makes helms work again. Majority of the code is on the Zeal side (0.6.3), but these server tweaks are the final thing we need to make the client/server compatibility the best it can be (I'd say perfect but donna wanna jinx it).
> ShowHelm now works as a personal toggle. Helm support will be fully compatible with next Zeal releases (0.6.3), fixing all known helm display issues.
People should never run into all the various janky helmet bugs again, and this sets us all up to have working helms for Velious as well. Also mostly handled by Zeal, but I did see a few IDs missing on the server (570 and 575) that I fixed.
Zeal PR is already merged into 0.6.3 branch, and it's working fine so far. https://github.com/iamclint/Zeal/pull/218

Feature - Clean up ShowHelm to work as personal helm toggle that is compatible with Zeal and Velious features

---

zone/gm_commands/togglepvp.cpp

Fixing this message
Can optionally remove it entirely, the red message also prints both ways.

Fix - #togglepvp message

---

zone/loot.cpp
zone/trading.cpp

Overlooked this edge case when you give a charm pet more items than it can equip, since it deletes & re-creates the item before moving it to the general inventory, so I missed this case for the S/SF information to be propagated.
> Fixed a S/SF Charm Pet loot bug that prevented looting pet items when you give a pet more weapons than it can equip.
E.g.
- Give pet 2 weapons to dual wield.
- **Give pet a 3rd weapon** (replaces one of the old weapons)
- SSF player can no longer loot the replaced weapon (bug, should be able to loot)

Fix - Handle edge case for SSF Charm Pet items

---

zone/spells.cpp
zone/zone.cpp

Based on discord PvP feedback, it seems everyone has been receptive to the following adjustments. So this PR enables:
- Allowing Selo's to be self-only.
- Allowing movement speed effects in outdoor PvP zones.

PvP: Speed effects enabled in outdoor zones. Bard Selos is self only.

---

common/eq_constants.h
common/eq_packet_structs.h
common/servertalk.h
zone/aggro.cpp
zone/attack.cpp
zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/client_process.cpp
zone/corpse.cpp
zone/corpse.h
zone/exp.cpp
zone/groups.cpp
zone/groups.h
zone/hate_list.cpp
zone/inventory.cpp
zone/lua_client.cpp
zone/lua_parser_events.cpp
zone/mob.cpp
zone/npc.cpp
zone/object.cpp
zone/raids.cpp
zone/raids.h
zone/spell_effects.cpp
zone/spells.cpp
zone/worldserver.cpp

Dialogue tree added to drop challenges (unless you are doing Null-class challenge).
- Hardcore -> Softcore
- Solo -> Self-Found Classic -> Self-Found Flex -> Normal
Testing - Confirmed existing behavior that we didn't re-add any of the nasty bugs
Additional SF Improvements
Notes
- A lot of the changes here were just about refactoring the logic that got bloated into a more manageable system, and the final result is that it is pretty straightforward to maintain now.
- Consolidated all the different ruleset variations of exp/loot/group-invite/raid-invite codepaths into a single codepath that is merged into the main exp/loot code (deleted a lot of copy/paste and one-off logic). Now we detect which `ChallengeRuleSet` is on each player, and the dominant `ChallengeRuleSet` for the group/raid …

Feature: SelfFound+

---

zone/client_packet.cpp

This is a minor bugfix but needs fixing due to PvP implications. The new logic fixes the server from getting into a bad state.

Fix: Server can put player into a bad state when Client tries to self-remove certain affects.

---

zone/client_packet.cpp

This patch makes it so we can use the `item.casttime_` field as the Instance/PVP override for clicky cast times, allowing us to nerf items in current expansion instances and pvp.
The Item table has a `casttime` and `casttime_` field, the latter was unused. So we can use that.
- If `casttime_` is `0` (default), it falls back to the default `casttime`.
- If `casttime_` is `-1` the spell becomes instant.
- Double checked all existing items, and `casttime_` is either 0 or equal to `casttime`, so it will not affect any current items.
- DB changes not included, that's up to ya'll on what you'd like to nerf or un-nerf in whichever scenarios.
- Tested both variations and they're working (casttime -> instant, and instant -> casttime)
```
UPDATE items set casttime_ = 4000 WHERE name like '%Undeads …
```

Feature: Adds support for Item casttime overrides while in current expansion Instances and PvP zones.

---

zone/client.cpp

Has no effect atm.
Improves tint support if we use it in the future.

Tweak: Supports Weapon tint colors sent on zone entry

---

common/eq_constants.h
common/ruletypes.h
zone/client.h
zone/client_packet.cpp

Server now sends an out-of-date warning message to clients using an old eqgame.dll
- Rule `Quarm:WarnDllVersionBelow` controls who gets the warning message.
- eqgame.dll defines its DLL_VERSION in eqgame.cpp and sends it during zone connection.
- All previous versions will show up as version 0. The new version going live soon will show up as version 1.
Improved Buff Stacking / Song Window handshake process.
- The upcoming (New/Fixed) eqgame.dll will be able to turn on Buff Stacking / Song Window.
- The existing/current versions will only get the "out-of-date" message and remain disabled.

Patch: Dll Versioning Support and Song Window V1/V2 detection

---

zone/mob.cpp

- SF loot was  sometimes being denied after Mez (memblur), because the from_memblur flag was not propagated.
This flag needed to be propagated, otherwise the progress towards doing majority damage kept getting reset every Mez if a blur procced.
There might be more going on with the SF loot deny bugs, but this one was a simple fix.

Fix SF loot deny bug caused by Mez

---

common/eq_constants.h
zone/client.cpp
zone/client.h
zone/spells.cpp

- Fixed a bug that allowed solo-self-found players to buff each other.
The `ChallengeRules::CanHelp()`, function had an incorrect assumption for Solo players since it was sharing code with Loot Rules, which does allow a Solo player to "loot with itself" (to simplify the Loot/Exp code, since they can't group with anyone but "themselves"). But caused a bug with buffing logic, since that can be done out of group, thus becoming "buff any Solo" rather than "buff myself".
Fixed by adding a dedicated  `ChallengeRules::CanHelp()` function that doesn't share code with Loot Rules, which always returns `false` for Solos receiving help.

Fix SSF players being able to buff each other

---

utils/sql/git/content/2025_03_01_AddKeyRing_HandOfGlory_Hole_Paineel.sql

Added key ring support for:
- Paineel Key
- Hole Key
- Hand of Glory*
- *Only gets added if you use the FINAL door in East Wing, behind Drusella's room at the exit pad (see screenshot)
- This door is HoG-only, so this door is safe to use as the keyring trigger, without causing the bugs that would previously happen that caused the NO RENT keyrings items to get saved. After using this final door with HoG, the whole zone is unlocked.

QoL: Correctly added Hand of Glory keyring + a couple other Key Rings

---

common/patches/mac.cpp
common/ruletypes.h
zone/attack.cpp
zone/client_packet.cpp
zone/client_process.cpp
zone/entity.cpp
zone/entity.h
zone/zone.cpp
zone/zone.h

- SF can repurchase items they sold to a vendor, equal to the amount they have sold (non-stackables only)

Self Found - Add support to recharge/repurchase items from vendors

---

zone/gm_commands/wc.cpp

Added extra user-friendly syntax for `#wc` command. All existing syntax still works.
- Can write any color value as base-10, base-16 (`0x` prefix) or base-2 (`0b` prefix)
Additionally supports `#wc <slot> <item> <Red> <Green> <Blue> [Alpha]`
- Allows expressing the color as discrete R G B values (0-255 each)
- Can optionally add a 4th value `[Alpha]`, which has no official use. But Quarm can use this as a `TintMask` for new tint features such as selective tinting.
Examples:
- `#wc 7 1 1052688` (old command, base10)
- `#wc 7 1 0x101010` (old command, base16)
- `#wc 7 1 16 16 16` (new command, individual rgb)
- `#wc 7 1 16 16 16 0b101` (new command that sets bit `1` and `3` of `TintMask`)

Improve usability of #wc command

---

zone/gm_commands/leaderboard.cpp

Some SFHC players mentioned that SF+ w/ HC wasn't showing on the leaderboard and suggested this fix.
Future proofing all the logic to `>= 1` instead of `= 1` for now as well, incase future adjustments are made. But we can revisit as needed.

Support SF+ being detected on leaderboards

---

zone/spells.cpp

This commit makes the classic era resists that I had previously implemented much more classic-like.  The previous commit was very incomplete and did not handle many Velious and Luclin boss spells and this is needed to fix that.  I've since better learned how resists were.  I will outline the changes because it probably looks strange as everybody is used to the new resist system and doesn't remember what it used to be like.
First it's important to understand that in classic, resists rolled a 0-99 instead of a 0-199.  Classic resists were more potent and in some ways resists became more unforgiving after the September 4 2002 revamp.  Post revamp, non-lure spells landed on players easier and also spells landing on NPCs became easier, which was a large DPS boost to caster players.  This meant …

Pseudoclassic Resists Updated

---

common/races.h
common/ruletypes.h
zone/entity.cpp
zone/mob.cpp

Added server-side support for the froglok stuff
- Race 330 returns true for IsPlayableRace (shared for both Classic/LoY model)
- `Illusion: Froglok` now applies race 330 to Clients.
- WearChange events turned on for race 330.
Misc
- Minor tweak to Velious helm 241 support to work more accurately (this texture is still unused). Unrelated.

PC Froglok Support

---

zone/spells.cpp

Please forgive the number of commits on this.  It's rather complicated to have two systems inside one method.
This commit will make druid dots, necro fire dots and lifetaps ignore the classic resist floors.
It also fixes a problem with both resist systems.  A partial damage modifier looked incorrect and I suspect that Prathun's pseudocode was wrong here or Sony otherwise botched it at some point after our era.  The Kunark decompiles show it the way I fixed it.

Resist system fixes

---

zone/spell_effects.cpp
zone/spells.cpp

This spell is Severilous and Wuoshi's AoE.  In all of our eras (including PoP) this spell did no damage.  Before the September 4 2002 resists revamp the spell was lure and difficult to resist.  Sony may have hardcoded it to not do damage because the spell data seemingly had a mistake in it which is the spell has no recast delay on it, which means the dragons casted it every few seconds.  Why they didn't just put a delay on it to fix it instead I don't know.
I made the spell do 1 dmage instead of zero because if set to zero damage the server doesn't send a spell packet to the client due to the way our logic works it would require more "if spell_id ==" crap to make it send packets at zero damage and I didn't want to clutter up the code with more of it.

Ceticious Cloud spell hardcodes

---

zone/spells.cpp

These are other edge cases I failed to consider earlier.  The player cast spells with a -1000 modifier (e.g. rapture, dictate) were spells Sony had hardcoded to be unresistable before they added the resist adjust field and wiz lures did a separate roll so they bypassed the floor.

Unresistable and wiz lure spells made to ignore classic resist floor

---

zone/spells.cpp

This PR fixes some bugs introduced introduced around Apr 5:
- Fixed a condition that wasn't updated when resist floor was change from 10% to 5%

fix: typo in conditition from resist change

---

zone/aggro.cpp

The bane spells did no or very little hate if casting from out of melee range, but they did full hate if standing inside melee range.  I verified this on Live servers just now.
The solution was to remove the resist type check which was allowing unresistable spells to still do hate.  I had put that there in 2015 because on Live I think I noticed Tash and Terror spells still doing hate but both of these lines had their hate generation characteristics changed after our timeline so I think it's likely they didn't do hate on bellycasters in our era.

Fixed hate for Velious era wizard bane spells

---

utils/sql/git/content/2025_04_14_PlaneOfMischief_Cards_Stackable.sql

- Makes PoM cards stackable.
These are pretty frustrating to sort through/manage, especially on self-found because we can't even mule them to banker alts. So we are limited to 1-per-card and have to resort to storing on corpses. Stackable would be really helpful.

Making PoM cards stackable

---

zone/special_attacks.cpp

- Fixed issue where Ranged Attack could not be used while singing
Bards were unable to throw items while in the middle of a song. Client-side decompiles (as well as just pushing the button being allowed) seems to indicate that it's allowed for bards, same as how most actions are allowed during bard songs.
From EQPlayer::DoAttack (used for combat abilities), see the CastingSpellId check. In fact it looks like it allows it for any spell, but allowing it just during songs seems fine.

Bug: Fixed issue where Ranged Attack could not be used while singing

---

utils/sql/git/content/2025_04_26_AddVelious_HelmetGraphics.sql

- Adds Velious 'custom helmet' graphics to some Velious helms that already had colors defined, but were missing a helmet graphic.
- Also adds a special graphic to Helmet of Rallos Zek (which previously had no visual).
Helmet of Rallos Zek
- Note: 'IT241' is a special unused ID that is a 'Rallos Zek'-style helmet when Ogres equip it. Looks like a regular Custom Helm on other races. 
Imbued Royal Velium Helmet
- No Drop. Blacksmithing. Part of Shawl 8 and fashion set.
Royal Velium Frosted Helmet
- No Drop. Icewell Keep guards. Part of fashion set.
Helm of the Deep Sea
- No Drop. Lord Koi`Doken.
Mischievous Dazzler Crown
- No Drop. PoM class crown.
Maleficent Crown
- No Drop. PoM class crown.
Wily Warlock Crown
- No Drop. PoM class crown.
Sly Summoner's Crown
- No Drop. PoM class crown.

Add Velious helmet graphics to a few helms

---

zone/attack.cpp
zone/corpse.cpp
zone/exp.cpp

- **Fixed bug where raid does not get loot rights if the 'killer' is not assigned to a group in the raid.**
- Note: _I think_ this is the reason why some mobs in a self-found raid were unlootable, as well as in normal raids, from time to time.
- I think I broke this when adjusting things for SF+ and moved a couple calls around.
- **Fixed bug where raid does not get loot lockout if the 'killer' is not assigned to a group in the raid.**
- Note: This is still handled via engagement records, so likely hasn't been exploited.
Comments:
- The `IsRaidGrouped()` check merely checks if the member in a raid is currently assigned to a group or not, and should not be used to determine the actual presence of the raid, because it's possible to be in a raid and also ungrouped.

Fix: Raid detection for raid loot rights and lockouts when ungrouped.

---

zone/buffstacking.cpp

- Fixes a server-side bug when `Spells:JamFestAAOnlyAffectsBard = false` which prevents bards from overwriting their own songs.
- Along with (optional dll fix) https://github.com/SecretsOTheP/akplus-dll/pull/16, we can now properly set `Spells:JamFestAAOnlyAffectsBard = false` making Jam Fest work properly.
When `Spells:JamFestAAOnlyAffectsBard = true`, the AA is actually a disadvantage and nerfs the player. It makes YOU take more damage from bards casting dots/DDs on you, such as in PvP, while your spells have NO improvement against other targets or buffing other targets. `Spells:JamFestAAOnlyAffectsBard = true` makes the AA a noob trap, making any bard that takes it nerfing themselves in PvP. So I highly suggest we turn the rule off with this patch. Plus turning it off makes the AA work …

Jam Fest - Fixes being unable to overwrite your own songs with Jam Fest AA

---

common/ruletypes.h
zone/special_attacks.cpp

Provides `Quarm:ArcheryCorneredDamage` and `Quarm:ArcheryWalledDamage` to permit tuning of archery damage for walled and cornered targets.
Intended to be used when `AlKabor:BlockProjectileWalls` and `AlKabor:BlockProjectileCorners` are disabled.

Add rules for walled/cornered archery damage

---

zone/client_packet.cpp
zone/inventory.cpp

- Resets AA Exp split back to 0% during NG+
- Prevents using AA Abilities until level 51 (like Dire Charm)

Block AA activation below level 51

---

zone/attack.cpp

There is a bug where sometimes you are able to hit a mob immediately upon death, after a fresh lockout is applied. This is a long-standing bug; I have logs of this happening a few different ways (damage shield kill via riposte, landing an offensive spell exactly as a mob dies, arrows hitting a mob after it is dead).
This has become a large issue for Rangers with the increased use of archery. I would estimate this happens on nearly 10% of boss deaths where an arrow is in-flight as the boss dies. I opened a bug in the PQ discord called "Kicked from zone on boss death - Archery" for this issue a couple weeks ago and decided I would try to find a fix myself.
This code adds an HP check around the client instance boot and only boots if the mob HP is greater than 0 i.e. not already dead. I can …

Instance boot 0 hp bug fix
