SecretsOTheP/EQMacEmu

utils/sql/git/required/2023_09_11_first_to_engage_table.sql
zone/client.h
zone/guild.cpp
zone/hate_list.cpp
zone/hate_list.h
zone/mob.cpp
zone/queryserv.cpp
zone/queryserv.h

Handle storing FTE into table via queryserv. 
Disengagement is stored as char_id=0, guild_name="", and engaged=0 since we don't need to store that information (it's possible to store it if we want though). Using the mob's name and time we should be able to deduce that information though.

FTE queryserv code

---

zone/client_packet.cpp

think it's spacing issue causing the other +/- changes

fix no rent items displaying

---

common/patches/evo.cpp
common/patches/evo_ops.h
common/patches/evo_structs.h
utils/patches/patch_Evo.conf

Needs compression disabled (`005f48b0` set to `0`)
Start zone mapping is incomplete
Zone entry fails due to `ServerZoneEntry_Struct` being 40 bytes short currently

Init evo character creation

---

zone/object.cpp

Code syntax errors

---

README.md

Added DB name and version number to help people understand how to install their own local db and inspect it

Update readme - Database version info

---

zone/client_packet.cpp

Allow ssf and sf players to pick up their own dropped items

Allow ssf and sf players to pick up their own dropped items

---

zone/spells.cpp

A common issue with not allowing normal players to cast spells on self found or solo players is they'll go through the casting process and it'll use their mana ( I suspect ), but either way they think they are about to buff or heal that player.
To help make things more clear, we'll interrupt the spells before they cast them and give them a good error message.
Didn't test or see if it compiles, but ChatGPT says it would probably compile, so might be worth testing before merging.

Interrupt beneficial spells that normies cast on self found or solo players to avoid wasting their mana

---

README.md

Hopefully this will be helpful for folks trying to test changes locally via Docker

Update README.md with local testing instructions

---

eqlaunch/eqlaunch.cpp
loginserver/main.cpp
queryserv/queryserv.cpp
ucs/clientlist.cpp
ucs/clientlist.h
ucs/database.cpp
ucs/ucs.cpp
world/net.cpp
world/ucs.cpp
world/ucs.h

- eqlaunch
- loginserver
- queryserv
- world
- ucs
- additional sending of world->ucs ServerOP_KeepAlive
Reference commits:
- https://github.com/EQEmu/Server/commit/77c3841a49886ac544fa3a0286ec760839992e67
- https://github.com/EQEmu/Server/commit/16cfad1966cacd63e0d0ab93be9ec48762312d69
Test by:
- building on msvc, gnu; playing the game

[Process Management] import changes from EQEmu to use EQ::EventLoop (libuv)

---

zone/attack.cpp

This is the method that computes an offense value for NPCs.  I modified it in this way:
* Non-pet NPCs level 46-50 now have the same offense value as a level 45.  This is because NPCs cap their weapon skill at 210 under level 51 and there is a very noticeable flattening of parsed NPC offense there.
* NPC summoned pets will now have the same lower offense values as player summoned pets.
* NPCs under level 6 could have their offense lowered too far from strength debuffs and now there's a floor.
* Improved the logic readability.

Refactored and improved Mob::GetOffense()

---

utils/sql/git/required/2024_07_11_character_reimbursements.sql
zone/client.h
zone/client_packet.cpp
zone/client_process.cpp
zone/zone.cpp
zone/zone.h
zone/zonedb.cpp
zone/zonedb.h

Merchant ID 1 will now function as a CSR tool - an item reimbursement merchant. 
All items on this merchant are temporary.
There will be future GM commands to manipulate the contents of this table. It's done by hand for now.

CSR Reimbursements via merchant id 1

---

utils/sql/git/content/2024_08_02_Ungate_Entities.sql

- Restore doors in Blackburrow
- Restore vendors in cities removed by TAKP merge

Ungate doors in Blackburrow and city vendors across the world.

---

utils/sql/git/content/2024_08_03_Ungate_BatchB.sql

- a shady goblin
- Dapper Blackhammer
- an_explorer (lakeofillomen)
- #a_lead_explorer (lakeofillomen)
- Weaponsmith_Ko`zirr
- #Hand_of_the_Maestro

Ungate new set of mobs.

---

utils/sql/git/content/2024_08_04_CazicThule_Alligator_Update.sql

split into 3 spawngroups. (level 20 to 24) (level 25 to 27) (level 28 to 33) 
change max level to 33.
Update pathgrid in alligator tunnel. 
level 20 to 27 will no longer aggro.

CazicThule Alligators update.

---

utils/sql/git/content/2024_08_09_Ungating.sql

- Ungate Oracle Qulin in Field of Bone for Iksar Shaman Cudgel quest
- Ungate a_skeleton in Najena

Ungate Oracle Qulin in FoB and a skeleton in Najena

---

utils/sql/git/content/2024_08_08_Ungate_Butcher_Goblin_and_Sword_of_Nobility.sql

- Ungate quest Blade of Nobility
- Ungate a goblin in Butcherblock for quest Blade of Nobility

Ungating for 2024-08-08

---

utils/sql/git/content/2024_08_12_Daily_Ungates.sql

- Added mage drops back to alligators in CT

Ungating requests for 2024-08-12

---

utils/sql/git/content/2024_08_17_Ungates_in_Steamfont.sql
utils/sql/git/content/2024_08_19_Ungating.sql

Ungate a_gnome_slave and minotaur_slaver near LFay zone line in Steamfont

Ungating in Steamfont

---

utils/sql/git/content/2024_10_14_Add_Cabilis_Self_Found_Enchant_Items.sql

Belner Snuckery, a smuggler from rivervale, husband to Mrs. Snuckery in the rogue guild has entered the sewers in Cabilis to provide self found players with a method to get enchanted bars and vials.
This is a sql script that needs to be run & there's also a parallel PR in the Quests repo - https://github.com/SecretsOTheP/quests/pull/44

Add new npc in cabilis to enchant metals for self found

---

utils/sql/git/content/2024_10_30_Enchanter_Epic_Modani_Easier.sql

Update the spawn rate to 100% up from 40%
Update the drop rate to 100% up from 88%
Update the spawn time to 15 minutes down from 40 minutes
Requested change thread: https://discord.com/channels/1133452007412334643/1299010475727654963
Tested by doing #repop and #npcloot show about 15 times and it met all of the criteria

Update Enchanter Epic Modani item to be easier to get

---

utils/sql/git/content/2024_10_31_Add_Starter_Food_Drink_Recipes.sql

Suggestion thread: https://discord.com/channels/1133452007412334643/1294093618776244306
Bread Cakes: clump of dough, muffin tin, yields 4, trivial 21
Skin of milk: bottle of milk, ruined pelt, yields 2, trivial 21

Add recipes for starter food and drink

---

zone/client.cpp

Not sure if there was a leeway (like +3 levels), but this change:
- Caps everything to your current level
- Applies the cap before skillmod bonuses, so skillmods will still work.
I checked `#showstats` while adjusting level and it was showing the proper ATK / Defense values changing this time (earlier was showing 450 Avoidance all the time, for example).

Fix - Cap skills while de-leveled

---

utils/sql/git/content/2024_12_20_Add_BAR_To_Some_PAL_Items.sql

Took a stab at what I think is a baseline list for suitable BAR / PAL items (See comments in SQL).
Can reduce down as needed.

Update - Adding 'BAR' to appropriate Paladin/Knight items

---

zone/inventory.cpp
zone/zonedb.cpp
zone/zonedb.h

Fix - NG+ Corpses

---

common/eq_constants.h
common/eq_packet_structs.h
common/patches/mac.cpp
common/patches/mac_structs.h
common/ruletypes.h
common/spdat.cpp
common/spdat.h
zone/bonuses.cpp
zone/buffstacking.cpp
zone/client.h
zone/client_packet.cpp
zone/mob.h
zone/npc.h

Status: Done.
- See other PR for full patch notes
Tried a bunch of scenarios, and the new buffstacking looks solid and feels good.
```
MyClass,  CasterClass,    CurrentBuff,    CastBuff,     With Patch                   Before Patch
Any       Bard            Selos           Travel        Overwrite                    Overwrite
Any       Any             Fungus          Jboots        Blocked                      Blocked
Any       SHM/Any         Jboots/SoW      Torpor        Stacks                       Stacks
Any       SHM/Any         Selos           Torpor        Stacks (Fixed/New)           Spell did not take hold (Bug)
Bard      Bard            Jboots          SoW/Fungus    Overwrite (Fixed)            Spell did not take hold (Bug)
Non-Bard  Non-Bard        Jboots          SoW/Fungus …
```

Feature: The Buff Stacking Patch

---

common/emu_constants.h
common/eq_constants.h
common/inventory_profile.cpp
common/inventory_profile.h
common/patches/mac.cpp
common/patches/mac_limits.h
common/ruletypes.h
common/shareddb.cpp
common/shareddb.h
utils/sql/git/required/2025_3_23_created_account_inventory_table.sql
zone/client.h
zone/client_packet.cpp
zone/client_process.cpp
zone/inventory.cpp
zone/trading.cpp
zone/zonedb.cpp

- 30 Bank Slots
- 0-30 Shared Bank Slots. Controlled by `Rule(Quarm, SharedBankBags)`

Feature: Extended Bank & Shared Bank

---

zone/client.cpp
zone/client.h
zone/command.cpp
zone/command.h
zone/gm_commands/takemoney.cpp

Adds a #takemoney command, similar to #givemoney, that takes the same parameters.

Add #takemoney command

---

utils/sql/git/content/2025_06_21_Sleepers_Tomb_Loot_Update.sql

Add ST 2.0 loot drops - itemize golem bosses, additional loot for warders

Add ST 2.0 loot

---

common/queue_packets.h
loginserver/client_manager.cpp
loginserver/world_server.cpp
loginserver/world_server.h
utils/scripts/queue_system/README.md
utils/scripts/queue_system/queue-system-test-interactive.sh
world/account_reservation_manager.cpp
world/account_reservation_manager.h
world/login_server.cpp
world/world_queue.cpp
world/world_queue.h

**Interactive Script & Tooling:**
- Got rid of queries to unused tables in the interactive script. Prettified and cleaned up live monitor. Added 'Kick by LSID', 'Move player to pos', 'Set cap', 'Set server ID' commands
- Enhanced interactive queue monitor script with improved server detection, new commands for setting population cap and server ID targeting
- Added intelligent server auto-detection to interactive script that reads server names from bin/eqemu_config.json and matches them against database registrations with robust fallback to latest server when configured names aren't found
**Database & Synchronization:**
- Added SyncQueueFromDatabase() for runtime sync between memory and database. Will auto sync in CheckForExternalChanges() when changes flag is set via interactive script
- …

Queue system improvements and database sync enhancements
